Virustotal: # Unlimited keys holds

  - # Your Virustotal API Key here

  - # Your Virustotal API key here


Chaos: # Unlimited or Limited keys - Your choice can holds both

  - # Your Chaos API Key here

  - # Another Chaos API Key here

Dnsdumpter: # Limited token and cookie holds

  csrf_cookie: # Your Dnsdumpter CSRF Cookie here

  csrf_token: # Your Dnsdumpter CSRF Token here

Whoisxml: # Unlimited keys holds

  - # Your Whoisxml API Key here

  - # Another Whoisxml API Key here

SecurityTrails: # Unlimited keys holds

  - # Your SecurityTrails API Key here

  - # Another SecurityTrails API Key here

Bevigil: # Unlimited keys

  - # Your Bevigil API Key here

  - # Another Bevigil API Key here

  - # Yet another Bevigil API Key here

Binaryedge: # Unlimited keys holds

  - # Your Binaryedge API Key here

  - # Another Binaryedge API Key here

  - # Yet another Binaryedge API Key here

Rapidapi: # Unlimited keys holds

  - # Your Rapidapi Key here

  - # Another Rapidapi Key here

Bufferover: # Unlimited keys holds

  - # Your Bufferover API Key here

  - # Another Bufferover API Key here

Certspotter: # Unlimited keys hods

  - # Your Certspotter API Key here

  - # Another Certspotter API Key here

Censys: # Limited Keys and ids holds

  api_secret_id: # Your Censys API Secret ID here

  api_secret_key: # Your Censys API Secret Key here

Fullhunt: # Unlimited keys holds

  - # Your Fullhunt API Key here

  - # Another Fullhunt API Key here

  - # Yet another Fullhunt API Key here

Leakix: # Unlimited keys holds

  - # Your Leakix API Key here

  - # Another Leakix API Key here

Netlas: # Unlimited keys holds

  - # Your Netlas API Key here

  - # Another Netlas API Key here

Zoomeye-API: # Unlimited keys holds

  - # Your Zoomeye-API Key here

Zoomeye-Auth: # Limited

  email: # Your Zoomeye Authentication Email here

  password: # Your Zoomeye Authentication Password here

Pushbullet-Notify: # Limited Keys holds

  - # Your Pushbullet API Key here
